//
//  Tools.swift
//  WriteVibe
//
//  Defines structures for AI tools and structured data generation that can be used by the language model.
//

import Foundation
#if canImport(FoundationModels)
import FoundationModels
#endif

// MARK: - AppTool Protocol

/// A protocol defining the structure for a callable tool that an AI model can use.
/// Named `AppTool` to avoid collision with `FoundationModels.Tool`.
protocol AppTool {
    var name: String { get }
    var description: String { get }
    func execute(arguments: String) async throws -> String
}

// MARK: - DateTimeTool

/// A tool that returns the current date and time.
struct DateTimeTool: AppTool {
    let name = "get_current_datetime"
    let description = "Returns the current date and time in ISO 8601 format."

    func execute(arguments: String) async throws -> String {
        // Arguments are typically expected in JSON format, but this tool takes none.
        // We can validate arguments if needed, but for simplicity, we ignore them.
        let dateFormatter = ISO8601DateFormatter()
        return dateFormatter.string(from: Date())
    }
}

// MARK: - Writing Analysis Data Structure

/// Represents the analysis of a piece of text, including tone, reading level, word count, and suggestions.
#if canImport(FoundationModels)
@available(macOS 26, *)
@Generable
struct WritingAnalysis {
    var tone: String // e.g., "Formal", "Informal", "Enthusiastic"
    var readingLevel: String // e.g., "Grade 8", "College"
    var wordCount: Int
    var sentenceCount: Int
    var avgWordsPerSentence: Float
    var passiveVoicePercent: Int   // 0–100
    var readabilityScore: String   // e.g. "Flesch-Kincaid Grade 9"
    var suggestions: [String]
}
#else
struct WritingAnalysis {
    var tone: String
    var readingLevel: String
    var wordCount: Int
    var sentenceCount: Int
    var avgWordsPerSentence: Float
    var passiveVoicePercent: Int
    var readabilityScore: String
    var suggestions: [String]
}
#endif


// MARK: - Tool Error

enum ToolError: Error {
    case invalidArguments(String)
    case executionFailed(String)
}

extension ToolError: LocalizedError {
    var errorDescription: String? {
        switch self {
        case .invalidArguments(let msg): return "Invalid arguments: \(msg)"
        case .executionFailed(let msg): return "Tool execution failed: \(msg)"
        }
    }
}

// MARK: - FoundationModels Tool Conformances & Structured Types

#if canImport(FoundationModels)

/// Extends `DateTimeTool` to conform to `FoundationModels.Tool` so it can be attached
/// to any `LanguageModelSession` that may reference the current date or time.
@available(macOS 26, *)
extension DateTimeTool: FoundationModels.Tool {
    @Generable struct Arguments {}

    func call(arguments: Arguments) async throws -> String {
        let formatter = ISO8601DateFormatter()
        return formatter.string(from: Date())
    }
}

// MARK: - ArticleOutline

/// Structured outline generated by Apple Intelligence from article metadata.
@available(macOS 26, *)
@Generable
struct ArticleOutline {
    var title: String
    var sections: [OutlineSection]

    @Generable
    struct OutlineSection {
        var heading: String
        var summary: String   // one-sentence description of what this section covers
    }
}

// MARK: - DraftVariants

/// Three distinct rewrites of a given passage, used by the Variants picker.
@available(macOS 26, *)
@Generable
struct DraftVariants {
    var variants: [String]   // exactly 3 items
}

// MARK: - WordCountPlan

/// Per-section word-count estimate for an article outline.
@available(macOS 26, *)
@Generable
struct WordCountPlan {
    var totalEstimate: Int
    var sections: [SectionEstimate]

    @Generable
    struct SectionEstimate {
        var heading: String
        var estimatedWords: Int
    }
}

// MARK: - OutlineTool

/// `@Tool` that generates a structured section outline on-device.
/// Intended for future use in a dedicated Apple Intelligence Copilot mode.
@available(macOS 26, *)
struct OutlineTool: FoundationModels.Tool {
    let name = "generate_section_outline"
    let description = "Generates a structured outline for a given article section heading and topic."

    @Generable struct Arguments {
        var heading: String
        var topic: String
    }

    func call(arguments: Arguments) async throws -> String {
        let outline = try await AppleIntelligenceService.generateOutline(
            title: arguments.heading,
            topic: arguments.topic,
            audience: "General",
            targetLength: "Medium"
        )
        return outline.sections
            .map { "- \($0.heading): \($0.summary)" }
            .joined(separator: "\n")
    }
}
#endif
